name: Scheduled Tests

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Run Tests
      run: cargo test --verbose
